### ISSUE TITLE
Problem in compiling the PySpice: os.waitpid OSError: No child processes

### ISSUE THREAD

**Issue by pedrohasselmann** [rca/PySPICE#20]
Hi,

I'm trying to compile the PySpice in my Windows 8 x64, with the x64 version of Python and cspice.
However, in build_cspice() I get the following error:

```
   In setup.py:
   os.waitpid(makeall.pid, 0)[1]
   OSError: [Errno 10] No child processes.
```

I identify the problem to be related with calling a inexistent csh installation path:

```
    os.chdir(CSPICE_SRC)
    makeall = Popen('/bin/csh makeall.csh', shell=True)
    status = os.waitpid(makeall.pid, 0)[1]
```

I see that the sentence was exclusively written to linux. How could I proceed?

**Comment by michaelaye** [comment]
Sorry, have no Windows. Maybe try our colleagues version of SPICE-Python implementation  https://github.com/AndrewAnnex/SpiceyPy, who did good work on making a more complete implementation. There's also a recently released Python-SPICE interface by the SETI institute, that should be pretty trustworthy as well: https://github.com/SETI/pds-tools. And last but not least, JPL's Horizon interface (which itself is an interface to SPICE) apparently also has an Python interface here: https://github.com/mihok/horizon-jpl but I don't know how powerful it is. Might be okay for simple stuff. For detailed SPICE work I would recommend either SpiceyPy or SETI's tools currently, if you can't install ours. I want to unify the different approaches next year, with a bit of luck. Am actually thinking of asking for funding to do this.

**Comment by drbitboy** [comment]
I know it worked under Cygwin at one point, but Michael's ideas sound better.

The makeall.csh call is not actually required since we always get a precompiled SPICE distribution, it's just my bias and habit to always re-compile on my local system.  So you could comment out those three lines for now, and we could update the script to not recompile either by default under a non-*x environment, or via a user-supplied NO_RECOMPILE_SPICE flag.

However, it is probably still true that the CSPICE_SRC variable (environment variable - a.k.a. "envvar" - in *x; I forget what it is or how to define it in Windows) must point to the correct CSPICE top level directory.

-b

**Comment by pedrohasselmann** [comment]
OK, thanks for help. I'm using the pds-tools for now, but I will keep checking your package updates.

 I'm not used to being a Windows guy, but the new ubuntu layout has not convinced me.

Pedro H.
